### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#132]

**Comment by tadaskay** [comment]
I guess this is related: when you apply from a non-existing file, it gives you a NPE rather than a proper message:
`applyFrom("asdf.gradle.kts")` ->
```
Caused by: kotlin.KotlinNullPointerException
        at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.<init>(KotlinBuildScriptCompiler.kt:49)
        at org.gradle.script.lang.kotlin.provider.KotlinScriptPluginFactory.compilerFor(KotlinScriptPluginFactory.kt:55)
        at org.gradle.script.lang.kotlin.provider.KotlinScriptPluginFactory.compile(KotlinScriptPluginFactory.kt:45)
        at org.gradle.script.lang.kotlin.provider.KotlinScriptPluginFactory.create(KotlinScriptPluginFactory.kt:38)
        at org.gradle.configuration.ScriptPluginFactorySelector.create(ScriptPluginFactorySelector.java:55)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:100)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:62)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:38)
        at Build_gradle.<init>(build.gradle.kts:17)
```

**Comment by bamboo** [comment]
It is. Thanks for the report @tadaskay!
