### ISSUE TITLE
Project can use `kotlin-gradle-plugin` 1.0.x 

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#189]
The recent upgrade to Kotlin 1.1-M03  (#187) broke Kotlin 1.0.x support.

To reproduce:

```
➜  gradle-script-kotlin git:(master) ✗ cd fixtures/plugin-compiled-against-kotlin-1.0 && ../../gradlew assemble
:compileKotlin
e: java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.platform.JavaToKotlinClassMap
        at org.jetbrains.kotlin.resolve.jvm.platform.JvmPlatform$defaultModuleParameters$1.getPlatformToKotlinClassMap(JvmPlatform.kt:35)
        at org.jetbrains.kotlin.descriptors.impl.ModuleDescriptorImpl.getPlatformToKotlinClassMap(ModuleDescriptorImpl.kt)
        at org.jetbrains.kotlin.context.ModuleContext$DefaultImpls.getPlatformToKotlinClassMap(context.kt:46)
        at org.jetbrains.kotlin.context.MutableModuleContext$DefaultImpls.getPlatformToKotlinClassMap(context.kt)
        at org.jetbrains.kotlin.context.MutableModuleContextImpl.getPlatformToKotlinClassMap(context.kt:90)
        ...
```

**Comment by bamboo** [comment]
Fixed by the upgrade to Kotlin 1.1.0-rc-91 (#264).
