### ISSUE TITLE
Can no longer run `hello-kotlin` sample application from IntelliJ

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#267]
After the update to the latest snapshot distro it's no longer possible to run the `hello-kotlin` sample from Intellij. It fails with:

```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at samples.HelloWorldKt.main(HelloWorld.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

Ilya Gorbunov [had the following to say](https://kotlinlang.slack.com/archives/eap/p1487611436000857) about a similar failure in another project:

> I've tried to import your project and seems all dependencies are imported with Provided scope.

![hello-kotlin failure screen shot](https://cloud.githubusercontent.com/assets/51689/23165604/c1b0fc58-f81b-11e6-86dd-df86fec36f91.png)

**Comment by bamboo** [comment]
This is actually an [IntelliJ issue](https://github.com/gradle/gradle/issues/1276#issuecomment-282495000).

**Comment by Roshankd1** [comment]
so what is the solution?

**Comment by bamboo** [comment]
@Roshankd1 Upgrade to IntelliJ IDEA 2017.1 or superior.

**Comment by Roshankd1** [comment]
@bamboo thanks for replying, I am actually trying to use this in Android studio 3.1
Is it possible?

**Comment by bamboo** [comment]
Hm, it seems a similar bug is still present in Android Studio 3.1.3:

```
Error: Could not find or load main class samples.HelloWorldKt
```

**Comment by Roshankd1** [comment]
@bamboo exactly i didnt want to load my pc with all the intellij :( and i have Xcode haha
