### ISSUE TITLE
"api" configuration extension method is not generated when using the 'java-library' plugin

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle-script-kotlin#287]
### Overview

The `api` configuration extension method for `DependencyHandler` is not generated.
This results in having to use the invoke style by doing `"api"("dependencyNotation")`.

My guess is that is because the configuration is `apiConfiguration.setVisible(false);`.

### Impact

<img width="107" alt="IntelliJ missing extension API" src="https://cloud.githubusercontent.com/assets/1447148/23390618/e27e3c20-fd34-11e6-9893-fd4d7327b293.png">

```
> Could not open cache directory 9t3fw39dt9byoj40h82pk8ubn (/Users/mkobit/.gradle/caches/3.5-20170227190532+0000/gradle-script-kotlin/9t3fw39dt9byoj40h82pk8ubn).
   > Internal error: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: No resolved call for 'api("org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion")' at (61,3) in /
Users/mkobit/Workspace/personal/junit/docker-junit-extension/build.gradle.kts
     Cause: No resolved call for 'api("org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion")' at (61,3) in /Users/mkobit/Workspace/personal/junit/docker-junit-extension/build.gradle.kts
     File being compiled and position: (61,3) in /Users/mkobit/Workspace/personal/junit/docker-junit-extension/build.gradle.kts
     PsiElement: api("org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion")
     The root cause was thrown at: callUtil.kt:188
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:324)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.genStatement(ExpressionCodegen.java:368)
```

### Version

GSK version: `distributionUrl = "https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170227190532+0000-all.zip"`

**Comment by bamboo** [comment]
Superseded by #337

**Comment by guenhter** [comment]
With gradle 4.6, this still not works
