### ISSUE TITLE
applyFrom causes an error due to duplicate generateKtsConfig 

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle-script-kotlin#6]
Looks like all `KotlinBuildScript`s try to create the task, so `applyFrom` doesn't work:

    Caused by: org.gradle.api.InvalidUserDataException: Cannot add task ':generateKtsConfig' as a task with that name already exists.
            at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:74)
            at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:97)
            at org.gradle.script.lang.kotlin.provider.KotlinScriptPlugin.registerBuiltinTasks(KotlinScriptPlugin.kt:59)
            at org.gradle.script.lang.kotlin.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:41)
            at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:102)
            at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:36)
            at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:62)
            at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
            at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:40)
            at org.gradle.script.lang.kotlin.KotlinBuildScript.apply(KotlinBuildScript.kt)
            at org.gradle.script.lang.kotlin.ProjectExtensionsKt.applyFrom(ProjectExtensions.kt:50)
            at Build_gradle.<init>(build.gradle.kts:18)
            at org.gradle.script.lang.kotlin.provider.KotlinScriptPlugin.instantiateScriptClass(KotlinScriptPlugin.kt:52)
            at org.gradle.script.lang.kotlin.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:42)

**Comment by cbeams** [comment]
Thanks for the report, @DanielThomas! We'll get this taken care of.
