### ISSUE TITLE
Support classpath entries pointing to directories

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#93]
Required to support the addition of `buildSrc` outputs to the script classpath. 

Currently fails with the following exception:

```
java.io.FileNotFoundException: Classpath entry points to a file that is not a JAR archive: /Users/bamboo/code/gradle/gradle-script-kotlin/buildSrc/build/resources/main 
java.lang.RuntimeException: java.io.FileNotFoundException: Classpath entry points to a file that is not a JAR archive: /Users/bamboo/code/gradle/gradle-script-kotlin/buildSrc/build/resources/main
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:119)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.getInjectedPsiFiles(InjectedGeneralHighlightingPass.java:185)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.collectInformationWithProgress(InjectedGeneralHighlightingPass.java:91)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
...
```

Blocking #92.

**Comment by ligee** [comment]
I wasn't able to reproduce precisely that behaviour, but I'm pretty sure this is because the path is incorrect, most likely - not existent. Unfortunately in the current version the code there is quite strict about such errors.
I prepared a fix that will tolerate such errors (because it is difficult to report them in a user-friendly manner at some places), so after the fix you'll not get errors and broken indices, but the dependency with wrong path will definitely be ignored.
The patch seems will not be a part of 1.1.-M1, so I'll prepare some custom build for you shortly after the release.

**Comment by bamboo** [comment]
Thanks @ligee.

Just to be perfectly clear, that error only happens within IDEA, not when compiling `build.gradle.kts` during a Gradle build.

**Comment by ligee** [comment]
Yes, I understand that. On the compilation you'd get compiler warning in this case.
